### ISSUE TITLE
Error in pop-before-smtp configuration && Enhancement request: support SMTP over SSL

### ISSUE THREAD

**Issue by tonsimple** [ankraft/smtpproxy#1]
Hi! 
I'm trying to use your proxy to get a stubborn stupid IOT device that only does unencrypted SMTP to send emails to Zoho via protected SMTP

Problem one: pop before SMTP plain doesn't work, with a strange error that kind of suggests that it expects "pop check delay" to be a boolean (its default, which I didn't change, is indeed not a boolean)

Traceback (most recent call last):
  File "smtpproxy.py", line 504, in <module>
    if readConfig() == False:
  File "smtpproxy.py", line 428, in readConfig
    account.rpopcheckdelay = smtpconfig.getboolean(s, 'popcheckdelay', account.rpopcheckdelay)
  File "/root/smtpproxy/config.py", line 42, in getboolean
    res = ConfigParser.getboolean(self, section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: 60

Problem two:
it does not properly work with SMTP servers that use SSL (NOT TLS) auth.
Zoho's TLS SMTP is notoriously broken , and doesn't work with this proxy (rejected with "authentication required").

Dunno why (it would be very kind of you if you tested this, but many, many softwares fail to work with Zoho TLS SMTP)

From prior experience with zoho, I have tried going the SSL (port 465) way (several ERPs I've worked with failed to connect to Zoho SMTP via TLS but succeeded with SSL SMTP) , but connection just times out.

**Comment by ankraft** [comment]
Thank you for your report.

Problem one: I confirm this bug. I'll fix it.

Problem two: I will check how much work this will be and whether I have access to an SMTP server that supports SSL. Perhaps I need your help to test this.

**Comment by tonsimple** [comment]
I've managed to figure out settings that work for Zoho SMTP via trial and error (posting here in case anyone else in the world is trying to get Zoho and SMTP proxy going)

[account@domain.com]
localhost=debian #(domain.com DOES NOT WORK!)
smtphost=smtp.zoho.com
smtpport=587
smtptls=true
smtpusername=account@domain.com #(assuming you use zoho to host a domain email)
smtppassword=your-password
popbeforesmtp=1
pophost=pop.zoho.com
popport=995
popssl=true
popusername=account@domain.com #(assuming you use zoho to host a domain email)
poppassword=your-password
popcheckdelay=1 #(it seems enough to get Zoho going and works around that "boolean thing")
returnpath=account@domain.com

**Comment by tonsimple** [comment]
[account@domain.com]
localhost=debian #(domain.com DOES NOT WORK!)
smtphost=smtp.zoho.com
smtpport=587
smtptls=true
smtpusername=account@domain.com #(assuming you use zoho to host a domain email)
smtppassword=your-password
popbeforesmtp=1
pophost=pop.zoho.com
popport=995
popssl=true
popusername=account@domain.com #(assuming you use zoho to host a domain email)
poppassword=your-password
popcheckdelay=1 #(it seems enough to get Zoho going and works around that "boolean thing")
returnpath=account@domain.com

**Comment by ankraft** [comment]
I just pushed version 1.5. This fixes the reported configuration error as well as supports smtp over ssl. 

Please note, that the configuration entry 'smtptls' is replaced by the new configuration option 'smtpsecurity'. Please see the documentation for that setting.
