### ISSUE TITLE
Duplicated else statment

### ISSUE THREAD

**Issue by Ark-PPC** [ankraft/smtpproxy#2]
https://github.com/ankraft/smtpproxy/blob/6a05b764743dca73e6114e904563749ab41c08da/smtpproxy.py#L458-L459

This else statment sets every account's port number to 25, maybe just a duplication of the previous two lines.

**Comment by ankraft** [comment]
Thanks for catching this. It seems I was a bit to eager with the defaults.

Please find the fix (removed the superfluous else statement) in the new 1.5.2 release.
