### ISSUE TITLE
Can I restrict mail sending in handlers ?

### ISSUE THREAD

**Issue by vanushwashere** [ankraft/smtpproxy#3]
As mentioned in title, how can I stop sending mail in handlers ?

**Comment by ankraft** [comment]
Not yet, but this sounds like a pretty good idea.

Could you elaborate on the details a bit? I would expect that when a mail handler returns, for example, false, then all processing stops, no further handler is called and the current mail is thrown away. Is this correct?

**Comment by vanushwashere** [comment]
Yeah, I think it is pretty good implementation

**Comment by vanushwashere** [comment]
I think I'll make it soon, as I need that in my project, and submit MR ;)

**Comment by ankraft** [comment]
I added this feature in the version 1.6.0.
MailHandler now have a return type.
When a MailHandler returns ```True```,  processing and sending continues normally. When it returns ```False``` then no further processing is done and the email is discarded.
